openapi: 3.0.1
info:
    title: B2W Planetas Star Wars
    description: API RESTful de planetas de Star Wars, feita para um desafio de back-end da B2W BIT
    contact:
        email: v@hnn.net.br
    version: 1.0.0
tags:
    - name: Planetas
      description: Informações sobre planetas
paths:
    /planetas:
        get:
            tags:
                - Planetas
            summary: Listar planetas
            operationId: getPlanetas
            responses:
                200:
                    description: Operação realizada com sucesso
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/InsertedPlaneta"
        post:
            tags:
                - Planetas
            summary: Adicionar novo planeta
            operationId: insertPlaneta
            requestBody:
                description: Planeta a ser adicionado no banco de dados
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Planeta"
            responses:
                201:
                    description: Planeta inserido com sucesso
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/InsertedPlaneta"
    /planetas/{planeta-id}:
        get:
            tags:
                - Planetas
            summary: Buscar planeta por id
            operationId: getPlanetById
            parameters:
                - name: planeta-id
                  in: path
                  description: ID do planeta a ser retornado
                  required: true
                  schema:
                    type: string
                    format: uuid
            responses:
                200:
                    description: Operação realizada com sucesso
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/InsertedPlaneta"
        delete:
            tags:
                - Planetas
            summary: Remover planeta por id
            operationId: deletePlanet
            parameters:
                - name: planeta-id
                  in: path
                  description: ID do planeta a ser removido
                  required: true
                  schema:
                    type: string
                    format: uuid
            responses:
                200:
                    description: Planeta removido com sucesso
    /planetas/by-nome/{planeta-nome}:
        get:
            tags:
                - Planetas
            summary: Buscar planeta por nome
            operationId: getPlanetByNome
            parameters:
                - name: planeta-nome
                  in: path
                  description: Nome do planeta a ser retornado
                  required: true
                  schema:
                    type: string
            responses:
                200:
                    description: Operação realizada com sucesso
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/InsertedPlaneta"
            
                                

components:
    schemas:
        Planeta:
            properties:
                nome:
                    type: string
                clima:
                    type: string
                terreno:
                    type: string
        InsertedPlaneta:
            allOf:
                - $ref: "#/components/schemas/Planeta"
            properties:
                id:
                    type: string
                    format: uuid
