version: "3"

services:
    planets-api:
        build: .
        depends_on: 
            - mongo
        ports:
            - 3000:3000
        environment:
            DB_USERNAME: mongo
            DB_PASSWORD: mongo
            DB_HOSTNAME: mongo
            DB_PORT: 27017
        volumes:
            - .:/app
    mongo:
        image: mongo
        volumes:
            - mongo:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: mongo
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongo

volumes:
    mongo:
