version: "3"

services:
    planets-api:
        build: .
        command: yarn run ${YARN_CMD:-watch}
        depends_on: 
            - mongo
        ports:
            - 3000:3000
            - 9229:9229
        environment:
            DB_STRING: "mongodb://mongo:27017/planetas"
            SWAPI_URL: "https://swapi.co/api"
            API_PORT: 3000
        volumes:
            - .:/app
    mongo:
        image: mongo
        volumes:
            - mongo:/data/db
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081

volumes:
    mongo:
